# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('comment_text', models.CharField(max_length=500)),
                ('comment_img', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(max_length=500)),
                ('updated_at', models.DateTimeField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Poses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_name', models.CharField(max_length=500)),
                ('pose_img', models.CharField(max_length=500)),
                ('difficulty_level', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('chakra', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('post_img', models.CharField(max_length=500)),
                ('post_video', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(max_length=500)),
                ('updated_at', models.DateTimeField(max_length=500)),
                ('pose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.Poses')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('profile_picture_img', models.CharField(max_length=500)),
                ('bio', models.CharField(max_length=500)),
                ('admin', models.BooleanField(default=False)),
                ('moderator', models.BooleanField(default=False)),
                ('professional', models.BooleanField(default=False)),
                ('verified_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.Users'),
        ),
        migrations.AddField(
            model_name='post_likes',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.Posts'),
        ),
        migrations.AddField(
            model_name='post_likes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.Users'),
        ),
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.Posts'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.Users'),
        ),
        migrations.AddField(
            model_name='comment_likes',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.Comments'),
        ),
        migrations.AddField(
            model_name='comment_likes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.Users'),
        ),
    ]
