# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0004_auto_20170522_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poses',
            old_name='pose_name_sankrit',
            new_name='pose_name_sanskrit',
        ),
        migrations.RenameField(
            model_name='poses',
            old_name='pose_name_sankrit_characters',
            new_name='pose_name_sanskrit_characters',
        ),
    ]
