# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0006_auto_20170522_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yoga.Posts'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yoga.Users'),
        ),
    ]
